# Generated by Django 5.2.8 on 2025-11-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='title',
            new_name='footer_title',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='text',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='time',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='profession',
        ),
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=models.TextField(default='Advertising office is a business that helps promoters in all phases of the advertising procedure – from record administration.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='period',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutskill',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pages.homepage'),
        ),
        migrations.AlterField(
            model_name='aboutskill',
            name='percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(upload_to='home/features/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/about/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_subtitle',
            field=models.CharField(default='Transforming brands with creativity', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_text',
            field=models.TextField(default='As a rule the organization settles on the inventive and media choices. Regularly it supplies supporting statistical surveying too, and may even be associated.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='ABOUT US', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/header/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_subtitle',
            field=models.TextField(default='Advertising is relied upon to impact the states of mind, expectations and conduct of the customer’s clients and in this way increment.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_title',
            field=models.CharField(default='We target the audience with our ideas.', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='disk_space',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='domains',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='pages.homepage'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='license',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='support',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='home/services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(default='', upload_to='home/testimonials/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
