# Generated by Django 5.2.8 on 2025-11-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_title_homepage_footer_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='features_subtitle',
            field=models.CharField(default='We have impressive Template Features', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_text',
            field=models.TextField(default='Advertising office is a business that helps promoters in all phases of the advertising procedure – from record administration and intending to message creation.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_title',
            field=models.CharField(default='FEATURES', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offers_badge',
            field=models.CharField(default='THE BEST OFFERS', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offers_title',
            field=models.CharField(default='OUR PRICING PLAN', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offers_toggle_left',
            field=models.CharField(default='Yearly Billing', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offers_toggle_right',
            field=models.CharField(default='Monthly billing', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor tincidunt neque vulputate vel sit ornare in ac. Aenean integer amet viverra sed gravida.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Our best services to solve Your problems.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius semper velit non nulla adipiscing nisl vel mi elementum.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_title',
            field=models.CharField(default='See what our clients say!', max_length=255),
        ),
    ]
